// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/token/token.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	token "github.com/jaysm12/multifinance-apps/pkg/token"
)

// MockTokenMethod is a mock of TokenMethod interface.
type MockTokenMethod struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMethodMockRecorder
}

// MockTokenMethodMockRecorder is the mock recorder for MockTokenMethod.
type MockTokenMethodMockRecorder struct {
	mock *MockTokenMethod
}

// NewMockTokenMethod creates a new mock instance.
func NewMockTokenMethod(ctrl *gomock.Controller) *MockTokenMethod {
	mock := &MockTokenMethod{ctrl: ctrl}
	mock.recorder = &MockTokenMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenMethod) EXPECT() *MockTokenMethodMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockTokenMethod) GenerateToken(arg0 token.TokenBody) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenMethodMockRecorder) GenerateToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenMethod)(nil).GenerateToken), arg0)
}

// ValidateToken mocks base method.
func (m *MockTokenMethod) ValidateToken(arg0 string) (token.TokenBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0)
	ret0, _ := ret[0].(token.TokenBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenMethodMockRecorder) ValidateToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenMethod)(nil).ValidateToken), arg0)
}
