port: 32001
postgres :
  postgres_config : <mysql_config>
hash :
  cost : 10
token :
  secret : <token_secret>
  exp_in_hour : 3
redis :
  host : localhost
  port : 6379
  password : <redis_password>
user_handler :
  timeout_in_sec : 5
auth_handler :
  timeout_in_sec : 5
partner_handler :
  timeout_in_sec : 5
max_find_counter : 10